spring:
  config:
    activate:
      on-profile: prod
  jpa:
    generate-ddl: false
    properties:
      "[hibernate.hbm2ddl.auto]": none
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
sentry:
  dsn:
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  logging:
    minimum-event-level: ERROR
    minimum-breadcrumb-level: DEBUG
    enabled: true
