spring:
  config:
    activate:
      on-profile: common
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    properties:
      "[hibernate.jdbc.time_zone]": UTC
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false
server:
  servlet:
    encoding:
      force-response: true
  error:
    include-exception: false
    include-message: always
    include-stacktrace: ON_PARAM
    whitelabel.enabled: false
springdoc:
  show-actuator: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    disable-swagger-default-url: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  model-and-view-allowed: true
