spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    properties:
      "[hibernate.jdbc.time_zone]": UTC
      "[hibernate.hbm2ddl.auto]": update
      "[hibernate.format_sql]": true
    defer-datasource-initialization: true
  batch:
    job:
      enabled: false
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: never
logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql]": trace
    "[org.hibernate.transaction.JDBCTransaction]": debug
    "[org.hibernate.jdbc.ConnectionManager]": debug
    "[org.springframework.orm.JpaTransactionManager]": debug
    "[org.springframework.jdbc]": debug
