spring:
  config:
    activate:
      on-profile: secret
  datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret: ${JWT_SECRET}
  access-expire: ${JWT_ACCESS_EXPIRE}
  refresh-expire: ${JWT_REFRESH_EXPIRE}
