spring:
  config:
    activate:
      on-profile: common
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    properties:
      "[hibernate.jdbc.time_zone]": UTC
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false
server:
  servlet:
    encoding:
      force-response: true
  error:
    include-exception: false
    include-message: always
    include-stacktrace: ON_PARAM
    whitelabel.enabled: false
