spring:
  config:
    activate:
      on-profile: secret-local
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/batch-postgresql-metadata-schema.sql
  datasource:
    url: jdbc:h2:mem:spring-boot-boilerplate;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379
auth:
  jwt:
    secret: "a9e8f7g6h5i4j3k2l1m0n9o8p7q6r5s4t3u2v1w0x9y8z7"
    access-expire: 10000000
    refresh-expire: 10000000000
  x-api-key: abcd1234-ef56-7890-ghij-1234567890kl
