spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/batch-postgresql-metadata-schema.sql
  datasource:
    url: jdbc:h2:mem:spring-boot-boilerplate;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    properties:
      "[hibernate.jdbc.time_zone]": UTC
      "[hibernate.hbm2ddl.auto]": create
      "[hibernate.format_sql]": true
    defer-datasource-initialization: true
logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql]": trace
    "[org.hibernate.transaction.JDBCTransaction]": debug
    "[org.hibernate.jdbc.ConnectionManager]": debug
    "[org.springframework.orm.JpaTransactionManager]": debug
    "[org.springframework.jdbc]": debug
