create table "user" (
  created_dt timestamp(6) not null,
  deleted_dt timestamp(6),
  updated_dt timestamp(6) not null,
  user_id bigint generated by default as identity,
  email varchar(255) not null unique,
  name varchar(255) not null,
  password varchar(255) not null,
  role enum ('ADMIN','MEMBER','USER') not null,
  primary key (user_id)
);

create table "post" (
  created_by bigint not null,
  created_dt timestamp(6) not null,
  post_id bigint generated by default as identity,
  updated_by bigint not null,
  updated_dt timestamp(6) not null,
  title varchar(20) not null,
  sub_title varchar(40) not null,
  content varchar(500) not null,
  user_id bigint,
  primary key (post_id),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES "user" (user_id)
);
